# safelist
branches:
  only:
  - master
  
language: php
#sudo: required
#dist: trusty
#group: edge
php:
  - '5.6'
  - hhvm

#cache:
directories:
  - src
install:
  - composer
before_script: composer require atoum/atoum
script: vendor/bin/atoum
before_script:
   - chmod 0777 ./src
services:
   - mysql
script:
  - cd ./src/tests
  - phpunit EmailTest.php
after_success:
   - mkdir -p codedeploy
   - zip -r neu-csye6225-Team2-ProjectCRM-${TRAVIS_JOB_NUMBER}.zip -i src appspec.yml || true
   - ls -al
   - mv neu-csye6225-Team2-ProjectCRM-${TRAVIS_JOB_NUMBER}.zip codedeploy || true
   - ls -al
   - pwd
   - cd codedeploy
   - ls -al
   - pwd
before_deploy:
   - cd ..
deploy:
 - provider: s3
   access_key_id: AKIAJHSK4OXYPAU33SIQ
   secret_access_key: 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
   local_dir: codedeploy
   bucket: code-deploy2.neu-csye6225-spring2017-team-2.com
   region: us-east-1
   skip_cleanup: true
 - provider: codedeploy
   access_key_id: AKIAJHSK4OXYPAU33SIQ
   secret_access_key: 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
   bucket: code-deploy2.neu-csye6225-spring2017-team-2.com
   key: neu-csye6225-Team2-ProjectCRM-${TRAVIS_JOB_NUMBER}.zip
   bundle_type: zip
   application: Team2Deployment7
   deployment_group: Team2Deployment7group
   region: us-east-1
   wait-until-deployed: true
