# safelist
branches:
  only:
  - master
  
language: php
#sudo: required
#dist: trusty
#group: edge
php:
  - '5.6'
  - hhvm
#  - nightly
#cache:
directories:
  - src
install:
  - composer
before_script:
str=$"/n"
sstr=$(echo -e $str)
apt-get install python-software-properties
apt-get update
apt-get -y install software-properties-common
apt-add-repository ppa:brightbox/ruby-ng
apt-get update
apt-get -y install ruby2.3
apt-get install ruby2.3-dev
apt-get update
apt-get install python-pip
apt-get install wget
cd /home/ubuntu
wget https://aws-codedeploy-us-east-1.s3.amazonaws.com/latest/install
chmod +x ./install
sudo ./install auto
service codedeploy-agent start
service codedeploy-agent status
apt-get install apache2 -y
a2enmod ssl
apt-get install openssl
a2enmod rewrite
LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php
echo "$sstr"
apt-get update
apt-get -y install php5.6 php5.6-mcrypt php5.6-mbstring php5.6-curl php5.6-cli php5.6-mysql php5.6-gd php5.6-intl php5.6-xsl php5.6-zip
service apache2 start
groupadd www
usermod -a -G www ubuntu
chown -R root:www /var/www
chmod 777 /var/www
find /var/www -type d -exec chmod 777 {} +
find /var/www -type f -exec chmod 777 {} +
echo "<?php phpinfo(); ?>" > /var/www/html/phpinfo.php
before_script:
   - chmod 0777 ./src
services:
   - mysql
script:
  - cd ./src/tests
  - phpunit EmailTest.php
#   - cd ./Team2Deployment7group/tests/EmailTest.php
#after_success:
#   - mkdir codedeploy
#   - zip -r neu-csye6225-Team2-ProjectCRM.zip src appspec.yml
#   - ls -al
#   - mv neu-csye6225-Team2-ProjectCRM.zip codedeploy/phpunit.xml
#   - ls -al
#   - pwd
#   - cd codedeploy
#   - ls -al
#   - pwd
#before_deploy:
#   - cd ..
#deploy:
# - provider: s3
#   access_key_id: AKIAJ2P47NBCEFNVPURA
#   secret_access_key:
#   secure: EOSLWmBq+82BEw1SLytsZkBBNAr7oFV6hh5Yl19fI1PcyC0rssgyajSzt/biAremCFqvoKHabVLjKXAxQbBUQHwLPX7tn/zBPSrIt8bDZY7wZc7lq1/y826Mo9EU3KTcnbZKjvAfC/3UIieg15txccIhwFexGtUygwj9knXlyjvAoi6xq2xwJr8lJo2mkf+aFuHIEXwl+KoY8zNANyO4dWA7iJ1ehEzOtTyASygOGgh3kD24+eP9bQynKBmMK1f5RUdBYVqi8BU70GxdDaN8kRQTbHtZS8TYb5j1G3n/aTOAv8lwvHLUyCpio0PkJdi7id+gILzqzRXSW9H8Hpz+DHGZd3S8ed+saZE5VgneFbwFoPk1vOq05K62EnMPanKvP7JMxy2XUPoNXM5YVxCsWkkOX32aGHEn+hnIB6rdypAY++DFnoYnodhOoBZVtT7uforwNIuFsH307crhCVRJ1UXVgRBR0aB9bE761F5PX/Znho4aSgi0fUgxusL328FOgfKo2Di+N8B+TWZSLXQvGep0Wm+eRDWQ2nneCIa9aXZ5uDxrhGLVrt4Qtie5Jl2xVVyJCaC9h9AGTO4OoE0PXLPBeQMbCPqxNyHrRGQzu2oqE1d1qxtG3myj6t3/9liFmCEv9fPB363NrHyTr5oeiEetW4QRIhTEJPXXJCJdjNM=
#   local_dir: codedeploy
#   bucket: code-deploy2.neu-csye6225-spring2017-team-2.com
#   region: us-east-1
#   skip_cleanup: true
# - provider: codedeploy
#   access_key_id: AKIAJ2P47NBCEFNVPURA
#   secret_access_key:
#   secure: EOSLWmBq+82BEw1SLytsZkBBNAr7oFV6hh5Yl19fI1PcyC0rssgyajSzt/biAremCFqvoKHabVLjKXAxQbBUQHwLPX7tn/zBPSrIt8bDZY7wZc7lq1/y826Mo9EU3KTcnbZKjvAfC/3UIieg15txccIhwFexGtUygwj9knXlyjvAoi6xq2xwJr8lJo2mkf+aFuHIEXwl+KoY8zNANyO4dWA7iJ1ehEzOtTyASygOGgh3kD24+eP9bQynKBmMK1f5RUdBYVqi8BU70GxdDaN8kRQTbHtZS8TYb5j1G3n/aTOAv8lwvHLUyCpio0PkJdi7id+gILzqzRXSW9H8Hpz+DHGZd3S8ed+saZE5VgneFbwFoPk1vOq05K62EnMPanKvP7JMxy2XUPoNXM5YVxCsWkkOX32aGHEn+hnIB6rdypAY++DFnoYnodhOoBZVtT7uforwNIuFsH307crhCVRJ1UXVgRBR0aB9bE761F5PX/Znho4aSgi0fUgxusL328FOgfKo2Di+N8B+TWZSLXQvGep0Wm+eRDWQ2nneCIa9aXZ5uDxrhGLVrt4Qtie5Jl2xVVyJCaC9h9AGTO4OoE0PXLPBeQMbCPqxNyHrRGQzu2oqE1d1qxtG3myj6t3/9liFmCEv9fPB363NrHyTr5oeiEetW4QRIhTEJPXXJCJdjNM=
#   bucket: code-deploy2.neu-csye6225-spring2017-team-2.com
#   key: neu-csye6225-Team2-ProjectCRM.zip
#   bundle_type: zip
#   application: CRMMavericksProject
#   deployment_group: Mavericks
#   region: us-east-1
#   wait-until-deployed: true
