# safelist
branches:
  only:
  - master
  
language: php
#sudo: required
#dist: trusty
#group: edge
php:
  - '5.6'
  - hhvm

#cache:
directories:
  - src
install:
  - composer
before_script:
 - str=$"/n"
 - sstr=$(echo -e $str)
 - sudo apt-get install python-software-properties
 - sudo apt-get update
 - sudo apt-get -y install software-properties-common
 - sudo apt-add-repository ppa:brightbox/ruby-ng
 - sudo apt-get update
 - sudo apt-get -y install ruby2.3
 - sudo apt-get install ruby2.3-dev
 - sudo apt-get update
 - sudo apt-get install python-pip
 - sudo apt-get install wget
 - cd /home/ubuntu
 - sudo wget https://aws-codedeploy-us-east-1.s3.amazonaws.com/latest/install
 - sudo chmod +x ./install
 - sudo ./install auto
 - sudo service codedeploy-agent start
 - sudo service codedeploy-agent status
 - sudo apt-get install apache2 -y
 - sudo a2enmod ssl
 - sudo apt-get install openssl
 - sudo a2enmod rewrite
 - sudo LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php
 - sudo echo "$sstr"
 - sudo apt-get update
 - sudo apt-get -y install php5.6 php5.6-mcrypt php5.6-mbstring php5.6-curl php5.6-cli php5.6-mysql php5.6-gd php5.6-intl php5.6-xsl php5.6-zip
 - sudo service apache2 start
 - sudo groupadd www
 - sudo usermod -a -G www ubuntu
 - sudo chown -R root:www /var/www
 - sudo chmod 777 /var/www
 - sudo find /var/www -type d -exec chmod 777 {} +
 - sudo find /var/www -type f -exec chmod 777 {} +
 - sudo echo "<?php phpinfo(); ?>" > /var/www/html/phpinfo.php
before_script:
   - chmod 0777 ./src
services:
   - mysql
script:
  - cd ./src/tests
  - phpunit EmailTest.php
after_success:
   - mkdir -p codedeploy
   - zip -r neu-csye6225-Team2-ProjectCRM.zip src appspec.yml || true
   - ls -al
   - mv neu-csye6225-Team2-ProjectCRM.zip codedeploy/ || true
   - ls -al
   - pwd
   - cd codedeploy
   - ls -al
   - pwd
before_deploy:
   - cd ..
deploy:
 - provider: s3
   access_key_id: AKIAJHSK4OXYPAU33SIQ
   secret_access_key: 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
   local_dir: codedeploy
   bucket: code-deployS3.neu-csye6225-spring2017-team-2.com
   region: us-east-1
   skip_cleanup: true
 - provider: codedeploy
   access_key_id: AKIAJHSK4OXYPAU33SIQ
   secret_access_key: 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
   bucket: code-deployS3.neu-csye6225-spring2017-team-2.com
   key: neu-csye6225-Team2-ProjectCRM.zip
   bundle_type: zip
   application: Team2Deployment7
   deployment_group: Team2Deployment7group
   region: us-east-1
   wait-until-deployed: true
