version: 0.0
os: linux
files:
  - source: ./appspec.yml
    destination: /home/ubuntu
  - source: ./index.php
    destination: /home/ubuntu
  - source: ./
    destination: /tmp/CRM

hooks:
  BeforeInstall:
    - location: ./scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: ./scripts/change_permissions.sh
      timeout: 300
      runas: root
  AfterInstall:
   - location:  ./scripts/restartTomcat.sh
     timeout: 300
     runas: root
  ApplicationStart:
    - location: ./scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: ./scripts/stop_server.sh
      timeout: 300
      runas: root
  
