version: 0.0
os: linux
files:
  - source: ./appspec.yml
    destination: /home/ubuntu
  - source: /index.php
    destination: /home/ubuntu
  - source: ./restartTomcat.sh
    destination: /home/ubuntu

hooks:
  AfterInstall:
   - location: ./restartTomcat.sh
     timeout: 180
     runas: ubuntu